// Static mock data for UI development and testing.

class ConnectionUser {
  final String id;
  final String firstName;
  final String middleName;
  final String lastName;
  final String email;
  final String phoneNumber;
  final String originCity;
  final String migratedCity;
  final String migratedCountry;
  final String educationCourse;
  final String specialization;
  final String collegeName;
  final String jobType;
  final String jobCompany;
  final List<String> connections;

  const ConnectionUser({
    required this.id,
    required this.firstName,
    required this.middleName,
    required this.lastName,
    required this.email,
    required this.phoneNumber,
    required this.originCity,
    required this.migratedCity,
    required this.migratedCountry,
    required this.educationCourse,
    required this.specialization,
    required this.collegeName,
    required this.jobType,
    required this.jobCompany,
    this.connections = const [],
  });
}

class MockData {
  MockData._();

  static final List<ConnectionUser> students = [
    const ConnectionUser(
      id: 's1',
      firstName: 'Ishaan',
      middleName: 'Kumar',
      lastName: 'Mehta',
      email: 'ishaan.mehta1@example.com',
      phoneNumber: '+919837963551',
      originCity: 'Rajkot',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'B.Tech Computer Science',
      specialization: 'Software Engineering',
      collegeName: 'Technical University of Berlin',
      jobType: 'Part-time',
      jobCompany: 'SAP',
      connections: ['s2', 's3'],
    ),
    const ConnectionUser(
      id: 's2',
      firstName: 'Nikhil',
      middleName: '',
      lastName: 'Patel',
      email: 'nikhil.patel2@example.com',
      phoneNumber: '+919891286393',
      originCity: 'Rajkot',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'B.Tech Computer Science',
      specialization: 'Software Engineering',
      collegeName: 'Technical University of Berlin',
      jobType: 'Part-time',
      jobCompany: 'SAP',
      connections: ['s3', 's4'],
    ),
    const ConnectionUser(
      id: 's3',
      firstName: 'Meera',
      middleName: '',
      lastName: 'Desai',
      email: 'meera.desai3@example.com',
      phoneNumber: '+919878163758',
      originCity: 'Rajkot',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'B.Tech Computer Science',
      specialization: 'Software Engineering',
      collegeName: 'Technical University of Berlin',
      jobType: 'Part-time',
      jobCompany: 'SAP',
      connections: ['s4', 's5'],
    ),
    const ConnectionUser(
      id: 's4',
      firstName: 'Aarti',
      middleName: '',
      lastName: 'Roy',
      email: 'aarti.roy4@example.com',
      phoneNumber: '+919813094462',
      originCity: 'Rajkot',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'B.Tech Computer Science',
      specialization: 'Software Engineering',
      collegeName: 'Technical University of Berlin',
      jobType: 'Part-time',
      jobCompany: 'SAP',
      connections: ['s5', 's6'],
    ),
    const ConnectionUser(
      id: 's5',
      firstName: 'Kartik',
      middleName: 'Kumar',
      lastName: 'Desai',
      email: 'kartik.desai5@example.com',
      phoneNumber: '+919828213452',
      originCity: 'Rajkot',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'B.Tech Computer Science',
      specialization: 'Software Engineering',
      collegeName: 'Technical University of Berlin',
      jobType: 'Part-time',
      jobCompany: 'SAP',
      connections: ['s6', 's1'],
    ),
    const ConnectionUser(
      id: 's6',
      firstName: 'Saurav',
      middleName: '',
      lastName: 'Khan',
      email: 'saurav.khan6@example.com',
      phoneNumber: '+919853550437',
      originCity: 'Rajkot',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'B.Tech Computer Science',
      specialization: 'Software Engineering',
      collegeName: 'Technical University of Berlin',
      jobType: 'Part-time',
      jobCompany: 'SAP',
      connections: ['s1', 's2'],
    ),
    const ConnectionUser(
      id: 's7',
      firstName: 'Ananya',
      middleName: 'Kumar',
      lastName: 'Pillai',
      email: 'ananya.pillai7@example.com',
      phoneNumber: '+919897880450',
      originCity: 'Ahmedabad',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Artificial Intelligence',
      specialization: 'Machine Learning',
      collegeName: 'Humboldt University of Berlin',
      jobType: 'Full-time',
      jobCompany: 'Siemens',
      connections: ['s8', 's9'],
    ),
    const ConnectionUser(
      id: 's8',
      firstName: 'Yash',
      middleName: '',
      lastName: 'Singh',
      email: 'yash.singh8@example.com',
      phoneNumber: '+919896520484',
      originCity: 'Ahmedabad',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Artificial Intelligence',
      specialization: 'Machine Learning',
      collegeName: 'Humboldt University of Berlin',
      jobType: 'Full-time',
      jobCompany: 'Siemens',
      connections: ['s9', 's10'],
    ),
    const ConnectionUser(
      id: 's9',
      firstName: 'Rohan',
      middleName: 'Kumar',
      lastName: 'Yadav',
      email: 'rohan.yadav9@example.com',
      phoneNumber: '+919860988088',
      originCity: 'Ahmedabad',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Artificial Intelligence',
      specialization: 'Machine Learning',
      collegeName: 'Humboldt University of Berlin',
      jobType: 'Full-time',
      jobCompany: 'Siemens',
      connections: ['s10', 's11'],
    ),
    const ConnectionUser(
      id: 's10',
      firstName: 'Aryan',
      middleName: 'Kumar',
      lastName: 'Desai',
      email: 'aryan.desai10@example.com',
      phoneNumber: '+919890914084',
      originCity: 'Ahmedabad',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Artificial Intelligence',
      specialization: 'Machine Learning',
      collegeName: 'Humboldt University of Berlin',
      jobType: 'Full-time',
      jobCompany: 'Siemens',
      connections: ['s11', 's12'],
    ),
    const ConnectionUser(
      id: 's11',
      firstName: 'Sneha',
      middleName: '',
      lastName: 'Mehta',
      email: 'sneha.mehta11@example.com',
      phoneNumber: '+919812110710',
      originCity: 'Ahmedabad',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Artificial Intelligence',
      specialization: 'Machine Learning',
      collegeName: 'Humboldt University of Berlin',
      jobType: 'Full-time',
      jobCompany: 'Siemens',
      connections: ['s12', 's7'],
    ),
    const ConnectionUser(
      id: 's12',
      firstName: 'Meera',
      middleName: 'Kumar',
      lastName: 'Trivedi',
      email: 'meera.trivedi12@example.com',
      phoneNumber: '+919881522851',
      originCity: 'Ahmedabad',
      migratedCity: 'Berlin',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Artificial Intelligence',
      specialization: 'Machine Learning',
      collegeName: 'Humboldt University of Berlin',
      jobType: 'Full-time',
      jobCompany: 'Siemens',
      connections: ['s7', 's8'],
    ),
    const ConnectionUser(
      id: 's13',
      firstName: 'Karan',
      middleName: 'Kumar',
      lastName: 'Yadav',
      email: 'karan.yadav13@example.com',
      phoneNumber: '+919814268798',
      originCity: 'Jamnagar',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'B.E. Mechanical Engineering',
      specialization: 'Automotive',
      collegeName: 'Technical University of Munich',
      jobType: 'Part-time',
      jobCompany: 'BMW',
      connections: ['s14', 's15'],
    ),
    const ConnectionUser(
      id: 's14',
      firstName: 'Priya',
      middleName: '',
      lastName: 'Agarwal',
      email: 'priya.agarwal14@example.com',
      phoneNumber: '+919852576686',
      originCity: 'Jamnagar',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'B.E. Mechanical Engineering',
      specialization: 'Automotive',
      collegeName: 'Technical University of Munich',
      jobType: 'Part-time',
      jobCompany: 'BMW',
      connections: ['s15', 's16'],
    ),
    const ConnectionUser(
      id: 's15',
      firstName: 'Sneha',
      middleName: '',
      lastName: 'Patel',
      email: 'sneha.patel15@example.com',
      phoneNumber: '+919834665123',
      originCity: 'Jamnagar',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'B.E. Mechanical Engineering',
      specialization: 'Automotive',
      collegeName: 'Technical University of Munich',
      jobType: 'Part-time',
      jobCompany: 'BMW',
      connections: ['s16', 's17'],
    ),
    const ConnectionUser(
      id: 's16',
      firstName: 'Sneha',
      middleName: '',
      lastName: 'Yadav',
      email: 'sneha.yadav16@example.com',
      phoneNumber: '+919830608679',
      originCity: 'Jamnagar',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'B.E. Mechanical Engineering',
      specialization: 'Automotive',
      collegeName: 'Technical University of Munich',
      jobType: 'Part-time',
      jobCompany: 'BMW',
      connections: ['s17', 's18'],
    ),
    const ConnectionUser(
      id: 's17',
      firstName: 'Divya',
      middleName: '',
      lastName: 'Verma',
      email: 'divya.verma17@example.com',
      phoneNumber: '+919843149275',
      originCity: 'Jamnagar',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'B.E. Mechanical Engineering',
      specialization: 'Automotive',
      collegeName: 'Technical University of Munich',
      jobType: 'Part-time',
      jobCompany: 'BMW',
      connections: ['s18', 's13'],
    ),
    const ConnectionUser(
      id: 's18',
      firstName: 'Amit',
      middleName: 'Kumar',
      lastName: 'Roy',
      email: 'amit.roy18@example.com',
      phoneNumber: '+919866007527',
      originCity: 'Jamnagar',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'B.E. Mechanical Engineering',
      specialization: 'Automotive',
      collegeName: 'Technical University of Munich',
      jobType: 'Part-time',
      jobCompany: 'BMW',
      connections: ['s13', 's14'],
    ),
    const ConnectionUser(
      id: 's19',
      firstName: 'Divya',
      middleName: '',
      lastName: 'Mehta',
      email: 'divya.mehta19@example.com',
      phoneNumber: '+919866701925',
      originCity: 'Rajkot',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Robotics',
      specialization: 'Autonomous Systems',
      collegeName: 'Ludwig Maximilian University',
      jobType: 'Full-time',
      jobCompany: 'Audi',
      connections: ['s20', 's21'],
    ),
    const ConnectionUser(
      id: 's20',
      firstName: 'Arjun',
      middleName: 'Kumar',
      lastName: 'Iyer',
      email: 'arjun.iyer20@example.com',
      phoneNumber: '+919878392465',
      originCity: 'Rajkot',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Robotics',
      specialization: 'Autonomous Systems',
      collegeName: 'Ludwig Maximilian University',
      jobType: 'Full-time',
      jobCompany: 'Audi',
      connections: ['s21', 's22'],
    ),
    const ConnectionUser(
      id: 's21',
      firstName: 'Priya',
      middleName: '',
      lastName: 'Agarwal',
      email: 'priya.agarwal21@example.com',
      phoneNumber: '+919810431596',
      originCity: 'Rajkot',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Robotics',
      specialization: 'Autonomous Systems',
      collegeName: 'Ludwig Maximilian University',
      jobType: 'Full-time',
      jobCompany: 'Audi',
      connections: ['s22', 's23'],
    ),
    const ConnectionUser(
      id: 's22',
      firstName: 'Ananya',
      middleName: '',
      lastName: 'Trivedi',
      email: 'ananya.trivedi22@example.com',
      phoneNumber: '+919814630936',
      originCity: 'Rajkot',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Robotics',
      specialization: 'Autonomous Systems',
      collegeName: 'Ludwig Maximilian University',
      jobType: 'Full-time',
      jobCompany: 'Audi',
      connections: ['s23', 's24'],
    ),
    const ConnectionUser(
      id: 's23',
      firstName: 'Ishaan',
      middleName: 'Kumar',
      lastName: 'Khan',
      email: 'ishaan.khan23@example.com',
      phoneNumber: '+919851138026',
      originCity: 'Rajkot',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Robotics',
      specialization: 'Autonomous Systems',
      collegeName: 'Ludwig Maximilian University',
      jobType: 'Full-time',
      jobCompany: 'Audi',
      connections: ['s24', 's19'],
    ),
    const ConnectionUser(
      id: 's24',
      firstName: 'Aryan',
      middleName: 'Kumar',
      lastName: 'Verma',
      email: 'aryan.verma24@example.com',
      phoneNumber: '+919837369610',
      originCity: 'Rajkot',
      migratedCity: 'Munich',
      migratedCountry: 'Germany',
      educationCourse: 'M.S. Robotics',
      specialization: 'Autonomous Systems',
      collegeName: 'Ludwig Maximilian University',
      jobType: 'Full-time',
      jobCompany: 'Audi',
      connections: ['s19', 's20'],
    ),
    const ConnectionUser(
      id: 's25',
      firstName: 'Karan',
      middleName: '',
      lastName: 'Chauhan',
      email: 'karan.chauhan25@example.com',
      phoneNumber: '+919896919658',
      originCity: 'Ahmedabad',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'MBA Business Analytics',
      specialization: 'Data Analytics',
      collegeName: 'University of Toronto',
      jobType: 'Part-time',
      jobCompany: 'Deloitte',
      connections: ['s26', 's27'],
    ),
    const ConnectionUser(
      id: 's26',
      firstName: 'Rohan',
      middleName: 'Kumar',
      lastName: 'Joshi',
      email: 'rohan.joshi26@example.com',
      phoneNumber: '+919849350047',
      originCity: 'Ahmedabad',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'MBA Business Analytics',
      specialization: 'Data Analytics',
      collegeName: 'University of Toronto',
      jobType: 'Part-time',
      jobCompany: 'Deloitte',
      connections: ['s27', 's28'],
    ),
    const ConnectionUser(
      id: 's27',
      firstName: 'Kabir',
      middleName: 'Kumar',
      lastName: 'Malhotra',
      email: 'kabir.malhotra27@example.com',
      phoneNumber: '+919830666824',
      originCity: 'Ahmedabad',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'MBA Business Analytics',
      specialization: 'Data Analytics',
      collegeName: 'University of Toronto',
      jobType: 'Part-time',
      jobCompany: 'Deloitte',
      connections: ['s28', 's29'],
    ),
    const ConnectionUser(
      id: 's28',
      firstName: 'Pooja',
      middleName: 'Kumar',
      lastName: 'Malhotra',
      email: 'pooja.malhotra28@example.com',
      phoneNumber: '+919821094611',
      originCity: 'Ahmedabad',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'MBA Business Analytics',
      specialization: 'Data Analytics',
      collegeName: 'University of Toronto',
      jobType: 'Part-time',
      jobCompany: 'Deloitte',
      connections: ['s29', 's30'],
    ),
    const ConnectionUser(
      id: 's29',
      firstName: 'Ishaan',
      middleName: '',
      lastName: 'Patel',
      email: 'ishaan.patel29@example.com',
      phoneNumber: '+919810065352',
      originCity: 'Ahmedabad',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'MBA Business Analytics',
      specialization: 'Data Analytics',
      collegeName: 'University of Toronto',
      jobType: 'Part-time',
      jobCompany: 'Deloitte',
      connections: ['s30', 's25'],
    ),
    const ConnectionUser(
      id: 's30',
      firstName: 'Kunal',
      middleName: 'Kumar',
      lastName: 'Khan',
      email: 'kunal.khan30@example.com',
      phoneNumber: '+919870062901',
      originCity: 'Ahmedabad',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'MBA Business Analytics',
      specialization: 'Data Analytics',
      collegeName: 'University of Toronto',
      jobType: 'Part-time',
      jobCompany: 'Deloitte',
      connections: ['s25', 's26'],
    ),
    const ConnectionUser(
      id: 's31',
      firstName: 'Amit',
      middleName: '',
      lastName: 'Desai',
      email: 'amit.desai31@example.com',
      phoneNumber: '+919878806231',
      originCity: 'Jamnagar',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'M.S. Data Science',
      specialization: 'Big Data',
      collegeName: 'York University',
      jobType: 'Full-time',
      jobCompany: 'Accenture',
      connections: ['s32', 's33'],
    ),
    const ConnectionUser(
      id: 's32',
      firstName: 'Harsh',
      middleName: 'Kumar',
      lastName: 'Trivedi',
      email: 'harsh.trivedi32@example.com',
      phoneNumber: '+919832056236',
      originCity: 'Jamnagar',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'M.S. Data Science',
      specialization: 'Big Data',
      collegeName: 'York University',
      jobType: 'Full-time',
      jobCompany: 'Accenture',
      connections: ['s33', 's34'],
    ),
    const ConnectionUser(
      id: 's33',
      firstName: 'Pooja',
      middleName: '',
      lastName: 'Pillai',
      email: 'pooja.pillai33@example.com',
      phoneNumber: '+919818683146',
      originCity: 'Jamnagar',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'M.S. Data Science',
      specialization: 'Big Data',
      collegeName: 'York University',
      jobType: 'Full-time',
      jobCompany: 'Accenture',
      connections: ['s34', 's35'],
    ),
    const ConnectionUser(
      id: 's34',
      firstName: 'Ishaan',
      middleName: 'Kumar',
      lastName: 'Khan',
      email: 'ishaan.khan34@example.com',
      phoneNumber: '+919899403041',
      originCity: 'Jamnagar',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'M.S. Data Science',
      specialization: 'Big Data',
      collegeName: 'York University',
      jobType: 'Full-time',
      jobCompany: 'Accenture',
      connections: ['s35', 's36'],
    ),
    const ConnectionUser(
      id: 's35',
      firstName: 'Aryan',
      middleName: '',
      lastName: 'Nair',
      email: 'aryan.nair35@example.com',
      phoneNumber: '+919843159796',
      originCity: 'Jamnagar',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'M.S. Data Science',
      specialization: 'Big Data',
      collegeName: 'York University',
      jobType: 'Full-time',
      jobCompany: 'Accenture',
      connections: ['s36', 's31'],
    ),
    const ConnectionUser(
      id: 's36',
      firstName: 'Arjun',
      middleName: 'Kumar',
      lastName: 'Singh',
      email: 'arjun.singh36@example.com',
      phoneNumber: '+919871870722',
      originCity: 'Jamnagar',
      migratedCity: 'Toronto',
      migratedCountry: 'Canada',
      educationCourse: 'M.S. Data Science',
      specialization: 'Big Data',
      collegeName: 'York University',
      jobType: 'Full-time',
      jobCompany: 'Accenture',
      connections: ['s31', 's32'],
    ),
    const ConnectionUser(
      id: 's37',
      firstName: 'Divya',
      middleName: '',
      lastName: 'Sharma',
      email: 'divya.sharma37@example.com',
      phoneNumber: '+919880979011',
      originCity: 'Rajkot',
      migratedCity: 'Orlando',
      migratedCountry: 'Canada',
      educationCourse: 'B.S. Information Technology',
      specialization: 'Networking',
      collegeName: 'University of Central Florida',
      jobType: 'Part-time',
      jobCompany: 'Cisco',
      connections: ['s38', 's39'],
    ),
    const ConnectionUser(
      id: 's38',
      firstName: 'Divya',
      middleName: 'Kumar',
      lastName: 'Malhotra',
      email: 'divya.malhotra38@example.com',
      phoneNumber: '+919866858435',
      originCity: 'Rajkot',
      migratedCity: 'Orlando',
      migratedCountry: 'Canada',
      educationCourse: 'B.S. Information Technology',
      specialization: 'Networking',
      collegeName: 'University of Central Florida',
      jobType: 'Part-time',
      jobCompany: 'Cisco',
      connections: ['s39', 's40'],
    ),
    const ConnectionUser(
      id: 's39',
      firstName: 'Priya',
      middleName: 'Kumar',
      lastName: 'Khan',
      email: 'priya.khan39@example.com',
      phoneNumber: '+919846009231',
      originCity: 'Rajkot',
      migratedCity: 'Orlando',
      migratedCountry: 'Canada',
      educationCourse: 'B.S. Information Technology',
      specialization: 'Networking',
      collegeName: 'University of Central Florida',
      jobType: 'Part-time',
      jobCompany: 'Cisco',
      connections: ['s40', 's41'],
    ),
    const ConnectionUser(
      id: 's40',
      firstName: 'Kabir',
      middleName: '',
      lastName: 'Desai',
      email: 'kabir.desai40@example.com',
      phoneNumber: '+919895665121',
      originCity: 'Rajkot',
      migratedCity: 'Orlando',
      migratedCountry: 'Canada',
      educationCourse: 'B.S. Information Technology',
      specialization: 'Networking',
      collegeName: 'University of Central Florida',
      jobType: 'Part-time',
      jobCompany: 'Cisco',
      connections: ['s41', 's42'],
    ),
    const ConnectionUser(
      id: 's41',
      firstName: 'Yash',
      middleName: 'Kumar',
      lastName: 'Sharma',
      email: 'yash.sharma41@example.com',
      phoneNumber: '+919862300895',
      originCity: 'Rajkot',
      migratedCity: 'Orlando',
      migratedCountry: 'Canada',
      educationCourse: 'B.S. Information Technology',
      specialization: 'Networking',
      collegeName: 'University of Central Florida',
      jobType: 'Part-time',
      jobCompany: 'Cisco',
      connections: ['s42', 's37'],
    ),
    const ConnectionUser(
      id: 's42',
      firstName: 'Sneha',
      middleName: '',
      lastName: 'Desai',
      email: 'sneha.desai42@example.com',
      phoneNumber: '+919889194806',
      originCity: 'Rajkot',
      migratedCity: 'Orlando',
      migratedCountry: 'Canada',
      educationCourse: 'B.S. Information Technology',
      specialization: 'Networking',
      collegeName: 'University of Central Florida',
      jobType: 'Part-time',
      jobCompany: 'Cisco',
      connections: ['s37', 's38'],
    ),
  ];

  static List<ConnectionUser> get allUsers => students;

  /// Returns automatically generated groups based on similarities
  static Map<String, List<ConnectionUser>> getGroups() {
    final Map<String, List<ConnectionUser>> groups = {};
    for (var user in students) {
      final key = '\${user.migratedCity}-\${user.migratedCountry}-\${user.collegeName}-\${user.educationCourse}-\${user.jobCompany}-\${user.originCity}';
      if (!groups.containsKey(key)) {
        groups[key] = [];
      }
      groups[key]!.add(user);
    }
    return groups;
  }

  /// Returns users NOT already connected to [userId], as recommendations.
  static List<ConnectionUser> getRecommendations(String userId) {
    final me = allUsers.firstWhere(
      (u) => u.id == userId,
      orElse: () => students.first,
    );
    return allUsers.where((u) => u.id != userId && !me.connections.contains(u.id)).toList();
  }

  /// Returns users already connected to [userId].
  static List<ConnectionUser> getConnections(String userId) {
    final me = allUsers.firstWhere(
      (u) => u.id == userId,
      orElse: () => students.first,
    );
    return allUsers.where((u) => me.connections.contains(u.id)).toList();
  }
}
