// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACtp50vtzjzSVW-FUe9z1tqI58wbIJQGM',
    appId: '1:1071073494722:web:dd961748a382e3828e1d5b',
    messagingSenderId: '1071073494722',
    projectId: 'peerconnect-16e19',
    authDomain: 'peerconnect-16e19.firebaseapp.com',
    storageBucket: 'peerconnect-16e19.firebasestorage.app',
    measurementId: 'G-ZY0S8KPH71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmc4yl0VW-8YwUcp6FxdEW6KXSBqoT8Ac',
    appId: '1:1071073494722:android:2762a5c0acf34e198e1d5b',
    messagingSenderId: '1071073494722',
    projectId: 'peerconnect-16e19',
    storageBucket: 'peerconnect-16e19.firebasestorage.app',
  );

}